language: r
warnings_are_errors: false
sudo: false
cache: packages

repos:
  CRAN: https://cloud.r-project.org
  sebkranz: https://skranz-repo.github.io/drat/

r_github_packages:
  - skranz/testex

# environment variables set for all builds
env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions


r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

#r_packages:
#  - covr

notifications:
  email:
    recipients:
      - sebkranz@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

script:
  - R CMD build --no-build-vignettes --no-manual .
  - R CMD check *tar.gz
  - R CMD INSTALL *.tar.gz
#  - R CMD INSTALL --no-docs --no-html .
  - Rscript testex/run_et.r

after_failure:
  - Rscript testex/after.R

after_success:
  - Rscript testex/after.R
